engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
  - tests/**/*
  - vendor/**/*
  - "config.default.yml"
  - "composer.json"
  - "composer.lock"
  - "README.md"
  - "LICENSE.md"
  - "CHANGELOG.md"
  